### ISSUE TITLE
Schemas not installed by PIP

### ISSUE THREAD

**Issue by jpstaub** [stevenkfirth/xgbxml#1]
Configuration:
windows: 10
anaconda navigator: 1.9.12 
python: 3.8
pip: 20.1.1
xgbxml: 0.0.2

-Advisory >> No such file or directory: 'C:\\Users\\admin\\anaconda3\\envs\\Test\\lib\\site-packages\\xgbxml\\schemas\\GreenBuildingXML_Ver0.37.xsd'
	
-Corrective action >> Manually copied schemas from xgbxml github repo to the directory.

**Comment by stevenkfirth** [comment]
Now solved in version 0.0.3. 

Please upgrade to latest version using `pip` if needed.

Solved by adding the following lines to setup.cfg

```
[options.package_data]
* = *.xsd
```
